### ISSUE TITLE
Use DifferentiationInterface v0.6

### ISSUE THREAD

**Issue by ElOceanografo** [ElOceanografo/MarginalLogDensities.jl#30]
The [new release of DI](https://github.com/gdalle/DifferentiationInterface.jl/releases/tag/DifferentiationInterface-v0.6.0) introdcuced a few breaking changes, as well as some new features that could be useful for this package.

**Comment by gdalle** [comment]
Happy to help with the transition if necessary. In particular, sparsity support has greatly improved, and Enzyme support too

**Comment by ElOceanografo** [comment]
Thanks! I plan to get to this in the next few weeks. Based on the new features in DI, this update will be pretty substantial, and will likely involve me deleting a lot of my own code in this package :) . I will definitely reach out if I run into bugs/trouble. If you are excited about it and have free time, feel free to start digging around and opening issues or pull requests in the meantime.
